apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ocf-vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.14.5
  name: ocf-vault-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ocf-vault-secrets-operator
      app.kubernetes.io/name: vault-secrets-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ocf-vault-secrets-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vault-secrets-operator
        helm.sh/chart: vault-secrets-operator-1.14.5
    spec:
      containers:
      - args:
        - -leader-elect
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: ''
        - name: VAULT_ADDRESS
          value: http://ocf-vault:8200
        - name: VAULT_AUTH_METHOD
          value: kubernetes
        - name: VAULT_TOKEN_PATH
          value: ''
        - name: VAULT_KUBERNETES_PATH
          value: auth/kubernetes
        - name: VAULT_KUBERNETES_ROLE
          value: vault-secrets-operator
        - name: VAULT_APP_ROLE_PATH
          value: auth/approle
        - name: VAULT_RECONCILIATION_TIME
          value: '0'
        image: ricoberger/vault-secrets-operator:1.14.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: vault-secrets-operator
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: vault-secrets-operator
