apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: 'true'
  labels:
    app.kubernetes.io/instance: ocf-vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: ocf-vault
  namespace: vault
spec:
  rules:
  - host: vault.ocf.berkeley.edu
    http:
      paths:
      - backend:
          service:
            name: ocf-vault-active
            port:
              number: 8200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - vault.ocf.berkeley.edu
    secretName: vault-ingress-tls
