apiVersion: v1
data:
  auto-direct-node-routes: 'false'
  bpf-lb-external-clusterip: 'false'
  bpf-lb-map-max: '65536'
  bpf-map-dynamic-size-ratio: '0.0025'
  bpf-policy-map-max: '16384'
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: ''
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: '24'
  custom-cni-conf: 'false'
  debug: 'false'
  disable-cnp-status-updates: 'true'
  disable-endpoint-crd: 'false'
  enable-auto-protect-node-port-range: 'true'
  enable-bandwidth-manager: 'false'
  enable-bpf-clock-probe: 'true'
  enable-endpoint-health-checking: 'true'
  enable-health-check-nodeport: 'true'
  enable-health-checking: 'true'
  enable-hubble: 'true'
  enable-ipv4: 'true'
  enable-ipv4-masquerade: 'true'
  enable-ipv6: 'false'
  enable-ipv6-masquerade: 'true'
  enable-k8s-terminating-endpoint: 'true'
  enable-l2-neigh-discovery: 'true'
  enable-l7-proxy: 'true'
  enable-local-redirect-policy: 'false'
  enable-policy: default
  enable-remote-node-identity: 'true'
  enable-session-affinity: 'true'
  enable-well-known-identities: 'false'
  enable-xt-socket-fallback: 'true'
  hubble-disable-tls: 'false'
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: 'true'
  install-no-conntrack-iptables-rules: 'false'
  ipam: cluster-pool
  ipv4-native-routing-cidr: 10.0.0.0/8
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ''
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: 'true'
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: 'false'
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: cilium
