apiVersion: v1
data:
  oidc.config: 'clientID: argocd

    clientSecret: $oidc.keycloak.clientSecret

    issuer: https://auth.ocf.berkeley.edu/auth/realms/ocf

    name: Keycloak

    requestedScopes:

    - openid

    - profile

    - email

    - groups

    '
  repositories: '- url: https://github.com/ocf/kubernetes'
  resource.exclusions: "- apiGroups:\n  - cilium*\n  clusters:\n  - '*'\n  kinds:\n\
    \  - CiliumIdentity\n"
  url: https://argo.ocf.berkeley.edu
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
