apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: '1'
  labels:
    app: startupapicheck
    app.kubernetes.io/component: startupapicheck
    app.kubernetes.io/instance: ocf-cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/version: v1.6.1
    helm.sh/chart: cert-manager-v1.6.1
  name: ocf-cert-manager-startupapicheck
  namespace: cert-manager
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: startupapicheck
        app.kubernetes.io/component: startupapicheck
        app.kubernetes.io/instance: ocf-cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: startupapicheck
        app.kubernetes.io/version: v1.6.1
        helm.sh/chart: cert-manager-v1.6.1
    spec:
      containers:
      - args:
        - check
        - api
        - --wait=1m
        image: quay.io/jetstack/cert-manager-ctl:v1.6.1
        imagePullPolicy: IfNotPresent
        name: cert-manager
        resources: {}
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ocf-cert-manager-startupapicheck
