apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: ocf-cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.6.1
    helm.sh/chart: cert-manager-v1.6.1
  name: ocf-cert-manager-webhook:subjectaccessreviews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocf-cert-manager-webhook:subjectaccessreviews
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: ocf-cert-manager-webhook
  namespace: cert-manager
