apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ocf-cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.6.1
    helm.sh/chart: cert-manager-v1.6.1
  name: ocf-cert-manager-controller-issuers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocf-cert-manager-controller-issuers
subjects:
- kind: ServiceAccount
  name: ocf-cert-manager
  namespace: cert-manager
