apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ocf-elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: elastic-operator-view
rules:
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apm.k8s.elastic.co
  resources:
  - apmservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.k8s.elastic.co
  resources:
  - kibanas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprisesearch.k8s.elastic.co
  resources:
  - enterprisesearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - beat.k8s.elastic.co
  resources:
  - beats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.k8s.elastic.co
  resources:
  - agents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maps.k8s.elastic.co
  resources:
  - elasticmapsservers
  verbs:
  - get
  - list
  - watch
