apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
  name: elastic-operator-webhook
  namespace: elastic
spec:
  ports:
  - name: https
    port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: ocf-elastic
    app.kubernetes.io/name: elastic-operator
