apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: ocf-elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
  name: elastic-operator
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ocf-elastic
      app.kubernetes.io/name: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        checksum/config: 9455b285fab11d1043e797b4369668e2bdcc6710f9cb128b9a98589ba63557d5
        co.elastic.logs/raw: '[{"type":"container","json.keys_under_root":true,"paths":["/var/log/containers/*${data.kubernetes.container.id}.log"],"processors":[{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"error","to":"_error"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_error","to":"error.message"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"source","to":"_source"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_source","to":"event.source"}]}}]}]'
      labels:
        app.kubernetes.io/instance: ocf-elastic
        app.kubernetes.io/name: elastic-operator
    spec:
      containers:
      - args:
        - manager
        - --config=/conf/eck.yaml
        - --distribution-channel=helm
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WEBHOOK_SECRET
          value: elastic-operator-webhook-cert
        image: docker.elastic.co/eck/eck-operator:1.8.0
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: https-webhook
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 150Mi
        volumeMounts:
        - mountPath: /conf
          name: conf
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: elastic-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: elastic-operator
        name: conf
      - name: cert
        secret:
          defaultMode: 420
          secretName: elastic-operator-webhook-cert
